export { normalizeDriverSchema } from "./driver-schema.js"
export {
  BACKGROUND_INPUT_LADDER,
  FORCE_FLAG,
  FOREGROUND_FLAG,
  FRONTING_ACTIONS,
  KEYBOARD_TOOLS,
  KEY_ROUTE_ADVICE,
  deliveredForeground,
  keyRouteAdvice,
  refusalFor,
  withoutEscalationNudge,
  type Refusal,
} from "./policy.js"
export {
  ElementSchema,
  MENU_ROLES,
  PASSIVE_ROLES,
  WindowRecordSchema,
  diffLines,
  elementLine,
  elementLines,
  indexSnapshot,
  lineAddress,
  lineIdentity,
  shownValue,
  toolResultData,
  toolResultError,
  windowKind,
  withWindowKinds,
  withoutMenuBar,
  type Element,
  type LineOptions,
  type SnapshotIndex,
  type ToolResult,
  type ViewDelta,
  type WindowKind,
  type WindowRecord,
} from "./projection.js"
export {
  DELIVERY_MODE_ACTIONS,
  HELPER_REFERENCE,
  MAKO_ACTIONS,
  MAKO_ACTION_FLAGS,
  actionLine,
  makoFlagNames,
  programProperties,
  renderReference,
  returnsOf,
  signatureOf,
  summaryOf,
  type DriverTool,
  type ProgramProperties,
} from "./reference.js"
export {
  computerHelpers,
  type Action,
  type Actions,
  type ComputerHelpers,
  type FillResult,
  type RouteVerdicts,
  type SubmitResult,
  type Target,
} from "./steps.js"
