/** Shared, versioned with the engine. No task IDs, credentials or app guesses. */
export const controlJsDescription = `Control browsers and native apps using persistent JavaScript and the initialized control SDK. Prefer a purpose-built API/CLI when it directly supports the task.
The first call prints the SDK documentation once; read it before acting. Start with one discovery call:
- Browser work: await control.browsers()
- Native app work: await control.apps(); if the task already supplies a pid, use await control.windows(pid) instead.
If you already have exact target IDs, bind that target and observe it instead. Never guess IDs or silently substitute a browser.
Use top-level await; bindings persist and can be redeclared in later cells. The last expression, or a returned value, prints: strings as text, SDK results in compact forms, your own values as compact JSON. Wait with expect() or tab.waitFor(), never fixed sleeps. Images require emitImage(await handle.screenshot()).
Focused help: await control.help({topic:"actions"}). Call control.rewriteDocumentation() only if the documentation is no longer in your context. Await every operation, verify the exact outcome, and never replay unknown input. This tool waits for completion; there are no numeric continuation tickets.`

export const controlReplDocumentation = `Mako browser and computer use — persistent JavaScript over the control SDK
The control SDK shares one task session with the mako-control CLI: the same targets, leases, refs, recordings and input guards. MCP never starts a CLI subprocess.

Cells: use top-level await. const and let bindings persist and can be redeclared in later cells. The last expression prints, and console.log prints more: a string as itself, an SDK result in the compact form below, any other value as compact JSON exactly as you built it. Printing never changes the value; view.nodes, receipt.status and tabs.pages stay available to code. A cell may end with return value, but then it runs as a function and its declarations stay local, so keep what you need in state. state is shared with CLI exec programs, which run as async functions. Errors print as one line, Error code (outcome): message, followed by the calls that changed something before the failure, if any; those already happened, so observe instead of rerunning the cell. Ordinary errors and callbacks that throw after their cell keep bindings; a timeout, cancellation or worker fault resets them. Tabs, windows, leases and recordings survive a reset.

Targets: discover, then use exact IDs only. control.browsers() prints one browser per line: id "name" status → the call its state allows next; connect one only when that says so, with await control.connectBrowser(id), and never switch browsers after a failure. let tab=await control.openTab({browser:id,url}) opens a task tab; control.tabs(id) prints one open tab per line, ID first, and await control.claimTab({browser:id,tab}) takes one. Native: control.apps() prints running apps pid first, control.windows(pid) their windows window_id first, then let win=control.window({pid,window_id}). In code these are objects: (await control.browsers()).browsers, (await control.tabs(id)).pages. Binding never observes; reads and images are explicit.

Act on what you observed. await tab.observe() prints the page's title, URL and scroll position, then its accessible outline, one element per line, indented under its container: e12 button "Save" disabled. The leading e12 is its ref. Prose prints as text: lines with links inside as [name](e12), and each fact prints once: text a control's name already holds is left out. Text and unnamed list, row and cell lines carry no printed ref; view.nodes keeps every ref. observe({interactive:true}) prints only controls as a flat list. Long pages print in parts: the first line says rows 1–200 of 1450 and observe({offset:200}) reads on; narrow with observe({within:[{role,name}],match:{role,name},query,max}) instead when you know what you want. A filtered read (interactive or query) cannot prove absence. In code, view.get({role,name}).ref picks one element, view.nodes holds the rows as {ref?,role,name,depth,...} and view.select({role?,text?}) filters them. Roles are the browser's accessibility roles and can differ from a role attribute; copy them from observe(). Pass refs to tab.click(ref), setValue(ref,text), pressKey(key,{ref}) or selectOption(ref,{label}). A page ref names one element of the current document: it stays valid across later reads and screenshots until the next action on that tab, after which you observe again or use a locator. Native window refs (n12) belong to that window's latest observation only. A locator reads fresh and needs exactly one match: await tab.locator({role:'button',name:'Save'}).click(). A string name is exact; name:{prefix:'Draft'}, name:{contains:'draft'} or name:/^Draft/ match names that carry live text such as counts, times or shortcuts. Scope duplicates with within:[{role:'dialog',name:'Settings'}].

Verify, never sleep. A failed action throws. An action prints one line, dispatched set-text e4 · route · delivery, meaning the input was sent; no action checks its own effect, so check it yourself. await tab.expect({role,name,value?,states?,absent?},{timeoutMs}) polls fresh evidence for one element; tab.expect({url?,title?,text?,selector?,hidden?},{timeoutMs}), the same as tab.waitFor, waits on the page, where url, title and text are case-sensitive substrings. Both throw assertion-failed at the deadline. Text already on the page satisfies a wait at once, so to prove an action caused it, check its absence first or wait on something only the action produces. When an outcome is unknown, observe before deciding; never replay the input.

Page verbs: tab.evaluate(fn,...args) or tab.evaluate('expression') returns a JSON value from page JavaScript; the function runs in the page and cannot see your variables. tab.inspect(ref,{attributes?:['href'],styles?:['color']}) reads tag, text, the named attributes (default: the first 24 present), box, visibility and the named computed styles, without changing the page. tab.hover(ref), tab.drag(fromRef,toRef,{steps?}) for pointer and HTML5 drag and drop, tab.scrollIntoView(ref), tab.scroll({deltaY}), tab.navigate(url) and tab.dialog({}). Locators offer .hover(), .dragTo(otherLocator), .inspect() and .scrollIntoView(). Use these before tab.cdp(): raw CDP input skips ref and view checks.

Pixels and files: const shot=await tab.screenshot({region?}) prints its size and view token, never its pixels; emitImage(shot) shows it, and click({x,y,view:shot.view}) uses its coordinates (CSS pixels on pages). artifacts.save(name,value) writes JSON, or an image from screenshot(), to a file and returns {path,bytes}. Node modules load with await import('node:fs/promises') and the like. Large output spills whole to files; nothing is silently cut. checkpoint({remember}) and recall() keep bounded task notes in state.

More: await control.help({topic}) for one of discovery, connection, handles, actions, observations, assertions, recording, page, native, output or examples. This documentation is printed once per session; call control.rewriteDocumentation() only after it has left your context. Scripts are trusted local JavaScript, not an OS sandbox.`
