/** Shared, versioned with the engine. No task IDs, credentials or app guesses. */
export const controlJsDescription = `Control browsers and native apps using persistent JavaScript and the initialized control SDK. Prefer a purpose-built API/CLI when it directly supports the task.
The first call prints the SDK documentation once; read it before acting. Start with one discovery call:
- Browser work: await control.browsers()
- Native app work: await control.apps(); if the task already supplies a pid, use await control.windows(pid) instead.
If you already have exact target IDs, bind that target and observe it instead. Never guess IDs or silently substitute a browser.
Use top-level await; bindings persist and can be redeclared in later cells. The last expression, or a returned value, prints as compact JSON. Wait with expect() or tab.waitFor(), never fixed sleeps. Images require emitImage(await handle.screenshot()).
Focused help: await control.help({topic:"actions"}). Call control.rewriteDocumentation() only if the documentation is no longer in your context. Await every operation, verify the exact outcome, and never replay unknown input. This tool waits for completion; there are no numeric continuation tickets.`

export const controlReplDocumentation = `Mako browser and computer use — persistent JavaScript over the control SDK
The control SDK shares one task session with the mako-control CLI: the same targets, leases, refs, recordings and input guards. MCP never starts a CLI subprocess.

Cells: use top-level await. const and let bindings persist and can be redeclared in later cells. The last expression prints as compact JSON; console.log prints more. A cell may end with return value, but then it runs as a function and its declarations stay local, so keep what you need in state. state is shared with CLI exec programs, which run as async functions. Ordinary errors keep bindings; a timeout, cancellation or worker fault resets them. Tabs, windows, leases and recordings survive a reset.

Targets: discover, then use exact IDs only. Browser and app lists are objects, not arrays. const {browsers}=await control.browsers(); connect one only when its next field says so, with await control.connectBrowser(id), and never switch browsers after a failure. let tab=await control.openTab({browser:id,url}) opens a task tab; control.tabs(id) lists open tabs ({tab,title,url}) and await control.claimTab({browser:id,tab}) takes one. Native: control.apps() lists running apps, control.windows(pid) their windows, then let win=control.window({pid,window_id}). Binding never observes; reads and images are explicit.

Act on what you observed. const view=await tab.observe() lists each element's role, name and ref; observe({interactive:true}) keeps only controls, hiding text, list items and regions. view.get({role,name}).ref picks one element, view.nodes holds the rows as {ref?,role,name,depth,...} and view.select({role?,text?}) filters them. observe({within:[{role,name}],match:{role,name},query,max}) reads only part of the page. A filtered read (interactive or query) reports coverage.complete:false because it cannot prove absence. Roles are the browser's accessibility roles and can differ from a role attribute (a listitem outside a list reads as generic); copy them from observe(). Pass refs to tab.click(ref), setValue(ref,text), pressKey(key,{ref}) or selectOption(ref,{label}). A locator reads fresh and needs exactly one match: await tab.locator({role:'button',name:'Save'}).click(). A string name is exact; name:{prefix:'Draft'}, name:{contains:'draft'} or name:/^Draft/ match names that carry live text such as counts, times or shortcuts. Scope duplicates with within:[{role:'dialog',name:'Settings'}]. Each action invalidates that target's refs, so observe again before using another ref, or use locators. A page screenshot keeps refs.

Verify, never sleep. A failed action throws. A returned receipt {status:'dispatched',verification:'not-requested'} means the input was sent; no action checks its own effect, so check it yourself. await tab.expect({role,name,value?,states?,absent?},{timeoutMs}) polls fresh evidence, and await tab.waitFor({text?,selector?,url?,hidden?,networkIdle?},{timeoutMs}) waits on the page, with text a case-sensitive substring of the visible page text; both throw assertion-failed at the deadline. Text already on the page satisfies a wait at once, so to prove an action caused it, check its absence first or wait on something only the action produces. Incomplete coverage cannot prove absence. When an outcome is unknown, observe before deciding; never replay the input.

Page verbs: tab.evaluate(fn,...args) or tab.evaluate('expression') returns a JSON value from page JavaScript; the function runs in the page and cannot see your variables. tab.inspect(ref,{attributes?:['href'],styles?:['color']}) reads tag, text, the named attributes (default: the first 24 present), box, visibility and the named computed styles, without changing the page. tab.hover(ref), tab.drag(fromRef,toRef,{steps?}) for pointer and HTML5 drag and drop, tab.scrollIntoView(ref), tab.scroll({deltaY}), tab.navigate(url) and tab.dialog({}). Locators offer .hover(), .dragTo(otherLocator), .inspect() and .scrollIntoView(). Use these before tab.cdp(): raw CDP input skips ref and view checks.

Pixels and files: const shot=await tab.screenshot({region?}); emitImage(shot) shows it, and click({x,y,view:shot.view}) uses its coordinates (CSS pixels on pages). artifacts.save(name,value) writes JSON, or an image from screenshot(), to a file and returns {path,bytes}. Node modules load with await import('node:fs/promises') and the like. Large output spills whole to files; nothing is silently cut. checkpoint({remember}) and recall() keep bounded task notes in state.

More: await control.help({topic}) for one of discovery, connection, handles, actions, observations, assertions, recording, page, native, output or examples. This documentation is printed once per session; call control.rewriteDocumentation() only after it has left your context. Scripts are trusted local JavaScript, not an OS sandbox.`
