import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { harnessLabel } from "../electron/providers/harness-descriptors.js"
import type { ProviderHost } from "../electron/providers/host.js"
import { providerHost } from "../electron/providers/index.js"

/**
 * Writes `src/dev/harness-descriptors.ts`: what the host tells the renderer
 * about each harness that holds on any Mac, for the dev mock and the checks
 * that run without a host. `--check` fails when the file is behind the
 * harness definitions.
 *
 *   npm run harness:descriptors [-- --check]
 */

export const GENERATED_PATH = join(import.meta.dirname, "..", "src", "dev", "harness-descriptors.ts")

export function renderHarnessDescriptors(host: ProviderHost = providerHost): string {
  const descriptors = host.harnesses.list().map(({ provider, presentation }) => ({
    provider,
    displayName: harnessLabel(host, provider),
    presentation,
    defaults: host.profiles.get(provider)?.defaults,
    resumable: host.nativeRunners.get(provider) !== undefined,
  }))
  return [
    "// Generated by `npm run harness:descriptors` from the harness definitions. Do not edit.",
    'import type { HarnessDescriptor } from "@/lib/types"',
    "",
    "/** Every harness in Mako's order, as the host describes it on any Mac. */",
    `export const harnessDescriptors: Pick<HarnessDescriptor, "provider" | "displayName" | "presentation" | "defaults" | "resumable">[] = ${JSON.stringify(descriptors, null, 2)}`,
    "",
  ].join("\n")
}

if (import.meta.filename === process.argv[1]) {
  const rendered = renderHarnessDescriptors()
  if (process.argv.includes("--check")) {
    if (readFileSync(GENERATED_PATH, "utf8") !== rendered) {
      console.error("src/dev/harness-descriptors.ts is behind the harness definitions. Run: npm run harness:descriptors")
      process.exit(1)
    }
    console.log("Harness descriptors: the dev snapshot matches the definitions")
  } else {
    writeFileSync(GENERATED_PATH, rendered)
    console.log(`Wrote ${GENERATED_PATH}`)
  }
}
