import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { VOCABULARIES, type HarnessVocabulary } from "@mako/sessions/harnesses"
import { nativeToolNames } from "@mako/sessions/tool-identity"
import { LIVE_CAPABILITY_KEYS, LIVE_CAPABILITY_LABELS, type Capability } from "../electron/contracts/harness-capabilities.js"
import { harnessLabel } from "../electron/providers/harness-descriptors.js"
import { providerHost } from "../electron/providers/index.js"
import { uniqueCell } from "./harness-checklist.ts"
import { NO_SOURCE, storedDefinitions, toolsAcross } from "./native-tools.ts"

/**
 * Writes `docs/harness-concepts.md`: each harness's concepts side by side,
 * with its plan and question mechanisms and its capability catalog, so a
 * question like "where does Grok read skills" or "which harnesses can steer"
 * has one page to answer it. `--check` fails when the page is behind the
 * declarations.
 *
 *   npm run harness:concepts [-- --check]
 */

export const GENERATED_PATH = join(import.meta.dirname, "..", "docs", "harness-concepts.md")

const code = (values: readonly string[]) => values.length ? values.map((value) => `\`${value}\``).join(", ") : "none"
const label = (harness: string) => harnessLabel(providerHost, harness)

function fixtureListings(harness: string): string {
  const file = join(import.meta.dirname, "fixtures", "native-vocabulary", `${harness}-concepts.json`)
  if (!existsSync(file)) return "none"
  const fixture: { skills?: { via: string }; mcpConfig?: { via: string } } = JSON.parse(readFileSync(file, "utf8"))
  const sources = new Map<string, string[]>()
  for (const [kind, places] of [["skills", fixture.skills], ["MCP", fixture.mcpConfig]] as const)
    if (places) sources.set(places.via, [...sources.get(places.via) ?? [], kind])
  return [...sources].map(([via, kinds]) => `${via} (${kinds.join(", ")})`).join("; ") || "the build searched only"
}

function definitionsRow({ harness, tools }: HarnessVocabulary): string {
  const newest = storedDefinitions(harness).at(-1)
  if (!newest) return `| ${label(harness)} | none | | | | | ${NO_SOURCE.get(harness) ?? "not recorded"} |`
  const defined = [...toolsAcross(newest).values()].filter(({ tool }) => !tool.placeholder)
  const deferred = defined.filter(({ tool }) => tool.deferred).length
  const nested = defined.filter(({ tool }) => tool.within).length
  const notes = [deferred ? `${deferred} deferred` : "", nested ? `${nested} called from a script` : ""].filter(Boolean)
  const unlisted = Object.values(tools).filter((tool) => tool.unlisted).length
  return `| ${label(harness)} | ${newest.version} | ${newest.on} | ${defined.length}${notes.length ? ` (${notes.join(", ")})` : ""} | ${newest.configurations.length} | ${unlisted} | ${newest.source} |`
}

function state(capability: Capability): string {
  if (capability.state === "absent") return capability.by === "mako" ? "Mako gap" : "harness has none"
  return capability.state
}

function section(title: string, line: (vocabulary: HarnessVocabulary) => string): string[] {
  return [`## ${title}`, "", ...VOCABULARIES.map((vocabulary) => `- **${label(vocabulary.harness)}**: ${line(vocabulary)}`), ""]
}

export function renderHarnessConcepts(): string {
  const harnesses = VOCABULARIES.map(({ harness }) => harness)
  return [
    "<!-- Generated by `npm run harness:concepts` from packages/sessions/src/harnesses and the harness definitions. Do not edit. -->",
    "",
    "# Harness concepts",
    "",
    "What each harness reads, emits and does on its own, as its concepts declare. `npm run harness:self-report -- <harness>` searches the installed build for every declared instruction file and hook event, and where the harness lists its own skills or MCP servers without an account, runs that listing against a throwaway home holding a probe in each declared place. Cursor's SDK lists nothing without an agent, so its skill folders come from the root table in the SDK's bundle. `scripts/test-harness-concepts.ts` fails when a fixture lacks a name, a listing misses a place, or Mako reads or writes somewhere the harness doesn't.",
    "",
    "| Harness | Checked on | Version | Places confirmed by |",
    "| --- | --- | --- | --- |",
    ...VOCABULARIES.map(({ harness, concepts }) => `| ${label(harness)} | ${concepts.checked.on} | ${concepts.checked.version} | ${fixtureListings(harness)} |`),
    "",
    ...section("Instructions", ({ concepts: { instructions } }) =>
      `${code(instructions.files)}; rules ${code(instructions.rules)}; for every project ${code(instructions.user)}. ${instructions.order}`),
    ...section("Hooks", ({ concepts: { hooks } }) => "absent" in hooks ? `none. ${hooks.absent}` :
      `configured in ${code(hooks.config)}. ${hooks.events.length} events${hooks.composed ? " (names built at run time)" : ""}: ${code(hooks.events)}. ${hooks.control}`),
    ...section("Skills", ({ concepts }) => code(concepts.skills)),
    ...section("Commands", ({ concepts: { commands } }) => "absent" in commands ? `none. ${commands.absent}` : `${code(commands.folders)}${commands.note ? `. ${commands.note}` : ""}`),
    ...section("Subagent definitions", ({ concepts }) => code(concepts.agents)),
    ...section("MCP configuration", ({ concepts }) => code(concepts.mcpConfig)),
    ...section("Output", ({ concepts: { output } }) => `live: ${output.live}; one-shot: ${code(output.headless)}; sessions: ${output.store}`),
    ...section("Models", ({ concepts }) => concepts.models),
    "## Only this harness",
    "",
    "From each harness definition's `unique`: what carries it natively, and the declaration that shows it in Mako, or why none does.",
    "",
    "| Harness | Feature | Native | In Mako |",
    "| --- | --- | --- | --- |",
    ...harnesses.flatMap((harness) => (providerHost.harnesses.get(harness)?.unique ?? []).map((feature) =>
      `| ${label(harness)} | ${feature.name} | ${feature.native.replaceAll("|", "\\|")} | ${uniqueCell(feature).replaceAll("|", "\\|")} |`)),
    "",
    "## Tool definitions",
    "",
    "Each harness's tools as it defines them, recorded per version by `npm run harness:native-tools -- <harness>` into `scripts/fixtures/native-tools`. `scripts/test-native-tools.ts` fails when the newest defines a tool the vocabulary doesn't declare, when a declared tool is neither defined nor `unlisted` with a reason, or when a declared argument key isn't a parameter. `--diff <harness> <a> <b>` names what changed between two versions.",
    "",
    "| Harness | Version | Recorded | Tools | Configurations | Declared, unlisted | Source |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...VOCABULARIES.map(definitionsRow),
    "",
    "## Plan, questions and subagents",
    "",
    "| Harness | Plan | Plan exit | Question tools | Subagent tools |",
    "| --- | --- | --- | --- | --- |",
    ...harnesses.map((harness) => {
      const planning = providerHost.liveDrivers.get(harness)?.planning
      const plan = !planning ? "none" : planning.via === "mode" ? `mode \`${planning.mode}\`` : `setting \`${planning.option}\``
      return `| ${label(harness)} | ${plan} | ${code(nativeToolNames(harness, "plan-exit"))} | ${code(nativeToolNames(harness, "question"))} | ${code(nativeToolNames(harness, "agent"))} |`
    }),
    "",
    "## Capabilities",
    "",
    "Projected from each live driver (`electron/providers/live-capabilities.ts`); `npm run harness:doctor -- <harness>` prints the reasons.",
    "",
    `| Capability | ${harnesses.map(label).join(" | ")} |`,
    `| --- |${harnesses.map(() => " --- |").join("")}`,
    ...LIVE_CAPABILITY_KEYS.map((key) => `| ${LIVE_CAPABILITY_LABELS[key]} | ${harnesses.map((harness) => {
      const capability = providerHost.harnesses.get(harness)?.capabilities[key]
      return capability ? state(capability) : "?"
    }).join(" | ")} |`),
    "",
  ].join("\n")
}

if (import.meta.filename === process.argv[1]) {
  const rendered = renderHarnessConcepts()
  if (process.argv.includes("--check")) {
    if (!existsSync(GENERATED_PATH) || readFileSync(GENERATED_PATH, "utf8") !== rendered) {
      console.error("docs/harness-concepts.md is behind the declarations. Run: npm run harness:concepts")
      process.exit(1)
    }
    console.log("Harness concepts: the reference matches the declarations")
  } else {
    writeFileSync(GENERATED_PATH, rendered)
    console.log(`Wrote ${GENERATED_PATH}`)
  }
}
