// Generated by `npm run harness:descriptors` from the harness definitions. Do not edit.
import type { HarnessDescriptor } from "@/lib/types"

/** Every harness in Mako's order, as the host describes it on any Mac. */
export const harnessDescriptors: Pick<HarnessDescriptor, "provider" | "displayName" | "presentation" | "defaults" | "resumable" | "capabilities" | "usage">[] = [
  {
    "provider": "claude",
    "displayName": "Claude Code",
    "presentation": {
      "mark": {
        "viewBox": "0 0 24 24",
        "paths": [
          {
            "d": "M20.998 10.949H24v3.102h-3v3.028h-1.487V20H18v-2.921h-1.487V20H15v-2.921H9V20H7.488v-2.921H6V20H4.487v-2.921H3V14.05H0V10.95h3V5h17.998v5.949ZM6 10.949h1.488V8.102H6v2.847Zm10.51 0H18V8.102h-1.49v2.847Z",
            "fillRule": "evenodd"
          }
        ],
        "tint": "#D97757"
      }
    },
    "defaults": {
      "work": [
        {
          "model": "claude-opus-5-5",
          "options": {
            "effort": "high",
            "fast": false
          }
        }
      ]
    },
    "resumable": true,
    "capabilities": {
      "resume": {
        "state": "implemented",
        "via": "The Agent SDK's `resume` option with the session ID, after the session file is checked."
      },
      "residency": {
        "state": "implemented",
        "via": "Mako closes the process of an idle conversation, past the idle timeout or the warm pool, and never while a turn, approval, background task or subagent runs. The next message starts a new `claude` process that resumes the session from its file."
      },
      "turnRecovery": {
        "state": "implemented",
        "via": "Accepted: The SDK's echo of the prompt's user message, as the turn starts. Exit: The SDK stream's failure when the process dies settles the session failed and disconnected in one update, with the transcript found by session ID when no hook has reported it yet."
      },
      "fork": {
        "state": "implemented",
        "via": "The Agent SDK's `forkSession` at a checkpoint (`resumeSessionAt`)."
      },
      "steering": {
        "state": "implemented",
        "via": "A message sent while a turn runs joins the running query and is read at its next step.",
        "lands": "step"
      },
      "compaction": {
        "state": "implemented",
        "via": "The harness's own compaction, started by Mako's Compact action."
      },
      "planning": {
        "state": "implemented",
        "via": "Its plan mode; the plan reaches Mako through ExitPlanMode's `plan` input, built by answering its permission request. A reply to it goes with the refusal, in the deny message of ExitPlanMode's permission answer, which Claude reads as the tool's result."
      },
      "approvals": {
        "state": "implemented",
        "via": "The harness asks and reports each decision it applied."
      },
      "questions": {
        "state": "implemented",
        "via": "AskUserQuestion reaches Mako as a tool approval carrying its questions; the answers return as the tool's input."
      },
      "modes": {
        "state": "implemented",
        "via": "Claude Code's permission modes, set on the running query with `setPermissionMode`."
      },
      "nativeAgents": {
        "state": "implemented",
        "via": "Agent and Workflow tool calls and their sidechain messages."
      },
      "backgroundStop": {
        "state": "implemented",
        "via": "Stop interrupts and closes the Claude process, with or without a running turn, which ends its background tasks; the next prompt resumes the session. Mako declares no per-task stop affordance, so an interrupt stops them too."
      },
      "contextBreakdown": {
        "state": "implemented",
        "via": "The Agent SDK's `getContextUsage`, by category."
      }
    },
    "usage": {
      "context": {
        "state": "implemented",
        "via": "The main agent's last call: what it read, cached or not, and wrote."
      },
      "window": {
        "state": "implemented",
        "via": "The answering model's `contextWindow` in each result's `modelUsage`."
      },
      "compaction": {
        "state": "implemented",
        "via": "The compact boundary's `post_tokens`."
      },
      "tokens": {
        "state": "implemented",
        "via": "Each result's session totals, less what the process had counted before."
      },
      "cost": {
        "state": "implemented",
        "via": "Each result's `total_cost_usd`, less what the process had counted before."
      },
      "missedCalls": {
        "state": "absent",
        "by": "harness",
        "reason": "Claude Code's results never say they left a call out."
      },
      "resetCredits": {
        "state": "absent",
        "by": "harness",
        "reason": "Claude's usage report has no reset credits."
      },
      "contextBreakdown": {
        "state": "implemented",
        "via": "The Agent SDK's `getContextUsage`, by category."
      },
      "outsideMako": {
        "state": "implemented",
        "via": "Settings › Usage reads its own store, so sessions run outside Mako count too."
      }
    }
  },
  {
    "provider": "codex",
    "displayName": "Codex",
    "presentation": {
      "mark": {
        "viewBox": "0 0 24 24",
        "paths": [
          {
            "d": "M8.086.457a6.105 6.105 0 0 1 3.046-.415c1.333.153 2.521.72 3.564 1.7a.117.117 0 0 0 .107.029c1.408-.346 2.762-.224 4.061.366l.063.03.154.076c1.357.703 2.33 1.77 2.918 3.198.278.679.418 1.388.421 2.126a5.655 5.655 0 0 1-.18 1.631.167.167 0 0 0 .04.155 5.982 5.982 0 0 1 1.578 2.891c.385 1.901-.01 3.615-1.183 5.14l-.182.22a6.063 6.063 0 0 1-2.934 1.851.162.162 0 0 0-.108.102c-.255.736-.511 1.364-.987 1.992-1.199 1.582-2.962 2.462-4.948 2.451-1.583-.008-2.986-.587-4.21-1.736a.145.145 0 0 0-.14-.032c-.518.167-1.04.191-1.604.185a5.924 5.924 0 0 1-2.595-.622 6.058 6.058 0 0 1-2.146-1.781c-.203-.269-.404-.522-.551-.821a7.74 7.74 0 0 1-.495-1.283 6.11 6.11 0 0 1-.017-3.064.166.166 0 0 0 .008-.074.115.115 0 0 0-.037-.064 5.958 5.958 0 0 1-1.38-2.202 5.196 5.196 0 0 1-.333-1.589 6.915 6.915 0 0 1 .188-2.132c.45-1.484 1.309-2.648 2.577-3.493.282-.188.55-.334.802-.438.286-.12.573-.22.861-.304a.129.129 0 0 0 .087-.087A6.016 6.016 0 0 1 5.635 2.31C6.315 1.464 7.132.846 8.086.457Zm-.804 7.85a.848.848 0 0 0-1.473.842l1.694 2.965-1.688 2.848a.849.849 0 0 0 1.46.864l1.94-3.272a.849.849 0 0 0 .007-.854l-1.94-3.393Zm5.446 6.24a.849.849 0 0 0 0 1.695h4.848a.849.849 0 0 0 0-1.696h-4.848Z",
            "fillRule": "evenodd"
          }
        ],
        "tint": "currentColor",
        "gradient": [
          {
            "offset": 0,
            "color": "#B1A7FF"
          },
          {
            "offset": 0.5,
            "color": "#7A9DFF"
          },
          {
            "offset": 1,
            "color": "#3941FF"
          }
        ]
      }
    },
    "defaults": {
      "work": [
        {
          "model": "gpt-6.1-sol",
          "options": {
            "effort": "medium",
            "serviceTier": "default"
          }
        }
      ]
    },
    "resumable": true,
    "capabilities": {
      "resume": {
        "state": "implemented",
        "via": "`thread/resume` on the app-server with the thread ID."
      },
      "residency": {
        "state": "implemented",
        "via": "Mako closes the process of an idle conversation, past the idle timeout or the warm pool, and never while a turn, approval, background task or subagent runs. The next message starts a new `codex app-server` that resumes the thread."
      },
      "turnRecovery": {
        "state": "implemented",
        "via": "Accepted: The turn/start response, which names the turn Codex began, before any of the turn runs. Exit: The app-server's exit, or a stdin or spawn error, settles the session failed and disconnected in one update; the rollout path was reported when the thread started."
      },
      "fork": {
        "state": "implemented",
        "via": "`thread/fork` at a turn."
      },
      "steering": {
        "state": "implemented",
        "via": "`turn/steer` adds the message to the running turn, read at its next step.",
        "lands": "step"
      },
      "compaction": {
        "state": "implemented",
        "via": "The harness's own compaction, started by Mako's Compact action."
      },
      "planning": {
        "state": "implemented",
        "via": "The plan setting; the plan reaches Mako through The Plan collaboration mode's plan item, built by a message that asks for the implementation. A reply to it is the next message: the plan arrives as the turn ends and nothing waits on an answer."
      },
      "approvals": {
        "state": "implemented",
        "via": "The harness asks and reports each decision it applied."
      },
      "questions": {
        "state": "implemented",
        "via": "`request_user_input` requests, answered on their own channel; the thread's history retires answered ones."
      },
      "modes": {
        "state": "implemented",
        "via": "Each mode is an approval policy and sandbox, sent with each turn."
      },
      "nativeAgents": {
        "state": "implemented",
        "via": "`spawn_agent` calls and the agent threads they start."
      },
      "backgroundStop": {
        "state": "implemented",
        "via": "Stop terminates exact native terminal IDs before interruption and checks again after settlement, including child threads. Stopped turn IDs retain a bounded guard for commands reported after interruption; failed native termination disconnects instead of claiming cleanup. Checked on Codex 0.159.3: foreground child exit and same-session follow-up. Closing ends terminals and subagents before the app-server exits."
      },
      "contextBreakdown": {
        "state": "absent",
        "by": "harness",
        "reason": "The app-server reports token totals and the context window, not what fills it."
      }
    },
    "usage": {
      "context": {
        "state": "implemented",
        "via": "Codex's own reading in `thread/tokenUsage/updated`."
      },
      "window": {
        "state": "implemented",
        "via": "The model's window in the same reading."
      },
      "compaction": {
        "state": "implemented",
        "via": "Codex sends a new reading after compacting, before the compaction item completes."
      },
      "tokens": {
        "state": "implemented",
        "via": "The reading's thread total, less what it said before."
      },
      "cost": {
        "state": "absent",
        "by": "harness",
        "reason": "Codex reports tokens only and prices none of them."
      },
      "missedCalls": {
        "state": "absent",
        "by": "harness",
        "reason": "Codex's readings never say they left a call out."
      },
      "resetCredits": {
        "state": "implemented",
        "via": "ChatGPT's usage report lists the plan's reset credits, and the account's row spends one."
      },
      "contextBreakdown": {
        "state": "absent",
        "by": "harness",
        "reason": "The app-server reports token totals and the context window, not what fills it."
      },
      "outsideMako": {
        "state": "implemented",
        "via": "Settings › Usage reads its own store, so sessions run outside Mako count too."
      }
    }
  },
  {
    "provider": "cursor",
    "displayName": "Cursor",
    "presentation": {
      "mark": {
        "viewBox": "0 0 24 24",
        "paths": [
          {
            "d": "M22.106 5.68 12.5.135a.998.998 0 0 0-.998 0L1.893 5.68a.84.84 0 0 0-.419.726v11.186c0 .3.16.577.42.727l9.607 5.547a.999.999 0 0 0 .998 0l9.608-5.547a.84.84 0 0 0 .42-.727V6.407a.84.84 0 0 0-.42-.726Zm-.603 1.176L12.228 22.92c-.063.108-.228.064-.228-.061V12.34a.59.59 0 0 0-.295-.51l-9.11-5.26c-.107-.062-.063-.228.062-.228h18.55c.264 0 .428.286.296.514Z",
            "fillRule": "evenodd"
          }
        ],
        "tint": "currentColor"
      }
    },
    "defaults": {
      "work": [
        {
          "model": "claude-opus-5-5",
          "options": {
            "effort": "high",
            "fast": "false"
          }
        }
      ]
    },
    "resumable": true,
    "capabilities": {
      "resume": {
        "state": "implemented",
        "via": "`Agent.resume` over the SDK's local store; a `cursor-agent` store is imported into it first."
      },
      "residency": {
        "state": "implemented",
        "via": "Mako closes the process of an idle conversation, past the idle timeout or the warm pool, and never while a turn, approval, background task or subagent runs. The next message starts a new SDK child that resumes the agent; a run its killed child left active is expired by the next one (`run-records.ts`)."
      },
      "turnRecovery": {
        "state": "implemented",
        "via": "Accepted: The run ID the SDK returns for the sent message. Exit: The SDK child's exit, unless Mako closed it, settles the running turn and the session failed and disconnected in one update."
      },
      "fork": {
        "state": "implemented",
        "via": "Mako writes the conversation up to the fork point into a new agent in the SDK's store and resumes it, as the SDK has no fork of its own."
      },
      "steering": {
        "state": "implemented",
        "via": "A message sent while a run works cuts its current step short and the model continues with it.",
        "lands": "interrupt"
      },
      "compaction": {
        "state": "default",
        "reason": "Cursor summarizes the conversation on its server when the context fills, and the summary shows in the thread. Cursor accepts a summarize request from a local run, but SDK 1.0.31 has no way to send one."
      },
      "planning": {
        "state": "implemented",
        "via": "The plan setting; the plan reaches Mako through createPlan's `plan` argument, built by a message that asks for the implementation. A reply to it is the next message: createPlan asks nothing, so the turn ends with the plan."
      },
      "approvals": {
        "state": "absent",
        "by": "harness",
        "reason": "Local SDK runs expose no interactive approval request or answer method. Native tool availability and workspace hooks enforce access."
      },
      "questions": {
        "state": "absent",
        "by": "harness",
        "reason": "Cursor doesn't offer its model `askQuestion` in a local SDK run, in agent or Plan mode, even when the run asks for the tool by name. A question that did come would be declined by the SDK itself."
      },
      "modes": {
        "state": "no-op",
        "reason": "The SDK runs one mode, agent; Plan is a setting chosen with each message."
      },
      "nativeAgents": {
        "state": "implemented",
        "via": "`task` tool calls and the subagent runs they start."
      },
      "backgroundStop": {
        "state": "default",
        "reason": "The local SDK disposes the shells a run started when the run ends, and a run stays running while a subagent it started works, so neither outlives its turn, and Stop ends the run."
      },
      "contextBreakdown": {
        "state": "absent",
        "by": "harness",
        "reason": "The SDK reports a run's token usage, not what fills the context."
      }
    },
    "usage": {
      "context": {
        "state": "absent",
        "by": "harness",
        "reason": "Cursor's SDK reports what each turn spent, never how full the context is."
      },
      "window": {
        "state": "absent",
        "by": "harness",
        "reason": "Cursor's SDK names no model's window."
      },
      "compaction": {
        "state": "absent",
        "by": "harness",
        "reason": "With no context reading, a summary Cursor writes has no meter to update."
      },
      "tokens": {
        "state": "implemented",
        "via": "Each turn's `usage` message from the SDK."
      },
      "cost": {
        "state": "absent",
        "by": "harness",
        "reason": "Cursor's SDK reports tokens only and prices none of them."
      },
      "missedCalls": {
        "state": "absent",
        "by": "harness",
        "reason": "Cursor's usage messages never say they left a call out."
      },
      "resetCredits": {
        "state": "absent",
        "by": "harness",
        "reason": "Cursor's usage report has no reset credits."
      },
      "contextBreakdown": {
        "state": "absent",
        "by": "harness",
        "reason": "The SDK reports a run's token usage, not what fills the context."
      },
      "outsideMako": {
        "state": "absent",
        "by": "harness",
        "reason": "Cursor's SDK store keeps no token counts, so Settings › Usage counts only what Mako measured while running it."
      }
    }
  },
  {
    "provider": "opencode",
    "displayName": "OpenCode",
    "presentation": {
      "mark": {
        "viewBox": "0 0 24 24",
        "paths": [
          {
            "d": "M22 24H2V0h20zM17 4.8H7v14.4h10z"
          }
        ],
        "tint": "currentColor"
      }
    },
    "defaults": {
      "work": [],
      "none": "OpenCode's models are the person's own providers, so it starts on the model they configured."
    },
    "resumable": true,
    "capabilities": {
      "resume": {
        "state": "implemented",
        "via": "The session ID on a new `opencode serve`, which reads the session from its own store."
      },
      "residency": {
        "state": "implemented",
        "via": "Mako closes the process of an idle conversation, past the idle timeout or the warm pool, and never while a turn, approval, background task or subagent runs. The next message starts a new `opencode serve` that reopens the session."
      },
      "turnRecovery": {
        "state": "implemented",
        "via": "Accepted: The server's acceptance of the prompt into the session's inbox, or its echo on the event stream. Exit: The server's exit settles the session failed and disconnected in one update."
      },
      "fork": {
        "state": "implemented",
        "via": "`session.fork` at a message."
      },
      "steering": {
        "state": "implemented",
        "via": "A prompt sent while the session is busy is read at its next step.",
        "lands": "step"
      },
      "compaction": {
        "state": "implemented",
        "via": "The harness's own compaction, started by Mako's Compact action."
      },
      "planning": {
        "state": "implemented",
        "via": "Its plan mode; the plan reaches Mako through The Plan agent's reply to a step that ends its turn, built by a message to Build. A reply to it is the next message: the plan is the Plan agent's reply, and nothing waits on an answer."
      },
      "approvals": {
        "state": "implemented",
        "via": "The harness asks and reports each decision it applied."
      },
      "questions": {
        "state": "implemented",
        "via": "The `question` tool's form, answered with `form.reply`."
      },
      "modes": {
        "state": "implemented",
        "via": "Each mode is an OpenCode agent, switched on the running session with `session.switchAgent`."
      },
      "nativeAgents": {
        "state": "implemented",
        "via": "`subagent` task calls and the child sessions they start."
      },
      "backgroundStop": {
        "state": "implemented",
        "via": "Stop interrupts every subagent session still executing and then removes every running shell of the conversation's sessions, once the interrupted turn settles, and at once with no turn running; closing does both before the server exits. OpenCode 2.0.1 keeps a background shell and a background subagent through an interrupt, and a shell past its server's exit."
      },
      "contextBreakdown": {
        "state": "absent",
        "by": "harness",
        "reason": "OpenCode reports token totals per message, not what fills the context."
      }
    },
    "usage": {
      "context": {
        "state": "implemented",
        "via": "The main session's last step: what it read, cached or not, and wrote."
      },
      "window": {
        "state": "implemented",
        "via": "The model's context limit in OpenCode's provider catalog."
      },
      "compaction": {
        "state": "default",
        "reason": "OpenCode doesn't say what a compaction left, so the meter keeps its earlier reading, marked, until the next reply."
      },
      "tokens": {
        "state": "implemented",
        "via": "Each step's tokens."
      },
      "cost": {
        "state": "implemented",
        "via": "Each step's cost."
      },
      "missedCalls": {
        "state": "absent",
        "by": "harness",
        "reason": "OpenCode's steps never say they left a call out."
      },
      "resetCredits": {
        "state": "absent",
        "by": "harness",
        "reason": "OpenCode's providers report no reset credits to it."
      },
      "contextBreakdown": {
        "state": "absent",
        "by": "harness",
        "reason": "OpenCode reports token totals per message, not what fills the context."
      },
      "outsideMako": {
        "state": "implemented",
        "via": "Settings › Usage reads its own store, so sessions run outside Mako count too."
      }
    }
  },
  {
    "provider": "grok",
    "displayName": "Grok",
    "presentation": {
      "mark": {
        "viewBox": "0 0 24 24",
        "paths": [
          {
            "d": "m9.27 15.29 7.978-5.897c.391-.29.95-.177 1.137.272.98 2.369.542 5.215-1.41 7.169-1.951 1.954-4.667 2.382-7.149 1.406l-2.711 1.257c3.889 2.661 8.611 2.003 11.562-.953 2.341-2.344 3.066-5.539 2.388-8.42l.006.007c-.983-4.232.242-5.924 2.75-9.383.06-.082.12-.164.179-.248l-3.301 3.305v-.01L9.267 15.292M7.623 16.723c-2.792-2.67-2.31-6.801.071-9.184 1.761-1.763 4.647-2.483 7.166-1.425l2.705-1.25a7.808 7.808 0 0 0-1.829-1A8.975 8.975 0 0 0 5.984 5.83c-2.533 2.536-3.33 6.436-1.962 9.764 1.022 2.487-.653 4.246-2.34 6.022-.599.63-1.199 1.259-1.682 1.925l7.62-6.815",
            "fillRule": "evenodd"
          }
        ],
        "tint": "currentColor"
      }
    },
    "defaults": {
      "work": [
        {
          "model": "grok-4.7",
          "options": {
            "effort": "high"
          }
        }
      ]
    },
    "resumable": true,
    "capabilities": {
      "resume": {
        "state": "implemented",
        "via": "ACP `session/load` with the session ID."
      },
      "residency": {
        "state": "implemented",
        "via": "Mako closes the process of an idle conversation, past the idle timeout or the warm pool, and never while a turn, approval, background task or subagent runs. The next message starts a new `grok` ACP agent that loads the session, replaying its history."
      },
      "turnRecovery": {
        "state": "implemented",
        "via": "Accepted: The agent's first output of the turn, or the session/prompt response when nothing streams first. Exit: The connection's close aborts the turn, whose failed result then waits for the process exit, which settles the session failed and disconnected in one update, with the session's source located by its ID."
      },
      "fork": {
        "state": "implemented",
        "via": "Grok's `x.ai/session/fork` copies the session through the turn its saved updates counted when the turn ended (`targetPromptIndex`). A turn from before Mako counted it, or a fork into another folder, is imported."
      },
      "steering": {
        "state": "implemented",
        "via": "`_x.ai/interject` adds the message to the running turn, read at its next step.",
        "lands": "step"
      },
      "compaction": {
        "state": "implemented",
        "via": "The harness's own compaction, started by Mako's Compact action."
      },
      "planning": {
        "state": "implemented",
        "via": "Its plan mode; the plan reaches Mako through exit_plan_mode's plan, replaced by the plan file's text once approved, built by answering its permission request. A reply to it goes with the refusal, in the `feedback` of a cancelled `_x.ai/exit_plan_mode` answer, while a plan file exists; with none, Grok drops the words, so they go as the next message."
      },
      "approvals": {
        "state": "implemented",
        "via": "The harness asks; Mako sees only that its answer was submitted."
      },
      "questions": {
        "state": "implemented",
        "via": "`_x.ai/ask_user_question` requests from the `ask_user_question` tool."
      },
      "modes": {
        "state": "implemented",
        "via": "ACP `session/set_mode`."
      },
      "nativeAgents": {
        "state": "implemented",
        "via": "`spawn_subagent` calls and the sessions they start."
      },
      "backgroundStop": {
        "state": "implemented",
        "via": "While tasks run, Stop closes the session, which ends them, and resumes it in the same process, with or without a running turn. Stop's session/cancel ends a subagent's work with no turn running too, checked on grok 1.0.41. Closing sends session/close too."
      },
      "contextBreakdown": {
        "state": "absent",
        "by": "harness",
        "reason": "ACP's `usage_update` carries the context used and its size, nothing itemized."
      }
    },
    "usage": {
      "context": {
        "state": "implemented",
        "via": "The main agent's last call, from each `response_completed`."
      },
      "window": {
        "state": "implemented",
        "via": "The current model's `totalContextTokens`, in the reply that opens the session and in Grok's model-list updates."
      },
      "compaction": {
        "state": "implemented",
        "via": "`auto_compact_completed`'s `tokens_after`."
      },
      "tokens": {
        "state": "implemented",
        "via": "Each `turn_completed`'s usage."
      },
      "cost": {
        "state": "implemented",
        "via": "Each `turn_completed`'s `costUsdTicks`."
      },
      "missedCalls": {
        "state": "implemented",
        "via": "`usageIsIncomplete` on a turn's usage."
      },
      "resetCredits": {
        "state": "absent",
        "by": "harness",
        "reason": "Grok's usage report has no reset credits."
      },
      "contextBreakdown": {
        "state": "absent",
        "by": "harness",
        "reason": "ACP's `usage_update` carries the context used and its size, nothing itemized."
      },
      "outsideMako": {
        "state": "implemented",
        "via": "Settings › Usage reads its own store, so sessions run outside Mako count too."
      }
    }
  },
  {
    "provider": "devin",
    "displayName": "Devin",
    "presentation": {
      "mark": {
        "viewBox": "0 0 24 24",
        "paths": [
          {
            "d": "M2.033 9.867l2.554 1.483a.589.589 0 00.592 0l2.554-1.483.01-.008a.608.608 0 00.11-.084l.013-.015a.631.631 0 00.076-.1c.003-.005.008-.01.01-.016a.558.558 0 00.052-.125l.007-.028a.611.611 0 00.019-.14V7.868c0-.572.307-1.105.8-1.392a1.595 1.595 0 011.598 0l1.277.742a.54.54 0 00.129.053l.028.01c.044.01.088.015.133.016h.006l.013-.002a.587.587 0 00.27-.074l.011-.004 2.554-1.483a.596.596 0 00.297-.516V2.253a.595.595 0 00-.297-.516L12.293.257a.587.587 0 00-.591 0L9.148 1.737l-.01.01a.609.609 0 00-.109.083l-.014.015a.632.632 0 00-.076.1c-.003.005-.008.01-.01.016a.57.57 0 00-.052.124l-.007.028a.612.612 0 00-.018.14v1.483c0 .572-.307 1.105-.8 1.393a1.597 1.597 0 01-1.599 0l-1.276-.742a.603.603 0 00-.13-.053l-.028-.008a.658.658 0 00-.133-.018h-.02a.57.57 0 00-.269.074c-.003.002-.008.002-.012.005L2.033 5.872a.596.596 0 00-.297.515v2.966c0 .213.113.41.297.515z",
            "fillRule": "evenodd"
          },
          {
            "d": "M15.943 10.607a1.596 1.596 0 011.599 0l1.276.74c.041.025.085.04.13.055l.028.008c.043.01.088.016.133.018h.005c.005 0 .01-.002.014-.003a.474.474 0 00.122-.016l.021-.005a.616.616 0 00.126-.052c.004-.002.009-.002.013-.005l2.554-1.482a.597.597 0 00.297-.516V6.383a.596.596 0 00-.297-.515l-2.552-1.483a.587.587 0 00-.592 0l-2.553 1.482-.011.008a.61.61 0 00-.108.084l-.014.016a.637.637 0 00-.076.1c-.003.005-.008.01-.01.016a.57.57 0 00-.052.124l-.007.029a.612.612 0 00-.018.14v1.482c0 .572-.307 1.105-.8 1.393a1.597 1.597 0 01-1.599 0l-1.276-.742a.584.584 0 00-.13-.053l-.028-.008a.62.62 0 00-.133-.018h-.02a.587.587 0 00-.269.074l-.012.004L9.15 10a.596.596 0 00-.296.516v2.966c0 .212.112.409.296.515l2.554 1.483s.008.002.012.005c.04.022.082.04.126.052l.02.004a.57.57 0 00.123.017l.014.002h.006c.054 0 .108-.01.16-.025a.587.587 0 00.13-.054l1.277-.741a1.597 1.597 0 012.398 1.392v1.482c0 .049.007.095.019.14l.007.028a.619.619 0 00.051.125c.004.006.008.01.01.016a.6.6 0 00.076.1l.014.015c.033.032.069.06.108.084.004.002.006.006.011.008l2.554 1.483a.59.59 0 00.593 0l2.554-1.483a.597.597 0 00.296-.516v-2.965a.595.595 0 00-.296-.516l-2.554-1.483s-.008-.002-.012-.005a.54.54 0 00-.126-.051c-.007-.003-.013-.003-.02-.005a.635.635 0 00-.125-.017h-.018a.557.557 0 00-.16.026.588.588 0 00-.13.053l-1.276.742a1.595 1.595 0 01-1.598 0 1.615 1.615 0 010-2.785l-.005-.001z",
            "fillRule": "evenodd"
          },
          {
            "d": "M14.848 18.265l-2.554-1.482-.012-.005a.526.526 0 00-.126-.052c-.007-.002-.014-.002-.02-.005a.64.64 0 00-.124-.017h-.02a.56.56 0 00-.16.026.588.588 0 00-.13.053l-1.276.742a1.594 1.594 0 01-1.598 0c-.493-.286-.8-.82-.8-1.393V14.65a.563.563 0 00-.018-.14l-.008-.028a.604.604 0 00-.051-.124l-.01-.017a.603.603 0 00-.076-.1l-.014-.015a.596.596 0 00-.109-.084c-.003-.002-.005-.006-.01-.008L5.178 12.65a.587.587 0 00-.591 0l-2.554 1.483a.596.596 0 00-.297.516v2.965c0 .213.113.41.297.516l2.554 1.483.012.004a.618.618 0 00.267.074l.016.002h.007a.55.55 0 00.16-.026.584.584 0 00.129-.053l1.277-.742a1.597 1.597 0 012.398 1.393v1.482c0 .05.007.095.019.14l.007.028c.013.044.03.085.051.125l.01.016c.022.036.047.07.076.1l.014.015c.032.032.069.06.109.084l.01.008 2.554 1.483a.587.587 0 00.593 0l2.554-1.483a.596.596 0 00.296-.515v-2.966a.596.596 0 00-.296-.516h-.002z",
            "fillRule": "evenodd"
          }
        ],
        "tint": "#4E8DF6"
      }
    },
    "defaults": {
      "work": [
        {
          "model": "swe-2",
          "options": {
            "effort": "high"
          }
        }
      ]
    },
    "resumable": true,
    "capabilities": {
      "resume": {
        "state": "implemented",
        "via": "ACP `session/load` with the session ID."
      },
      "residency": {
        "state": "implemented",
        "via": "Mako closes the process of an idle conversation, past the idle timeout or the warm pool, and never while a turn, approval, background task or subagent runs. The next message starts a new `devin` ACP agent that loads the session, replaying its history."
      },
      "turnRecovery": {
        "state": "implemented",
        "via": "Accepted: The agent's first output of the turn, or the session/prompt response when nothing streams first. Exit: The connection's close aborts the turn, whose failed result then waits for the process exit, which settles the session failed and disconnected in one update, with the session's source located by its ID."
      },
      "fork": {
        "state": "implemented",
        "via": "Devin's revert extension: `forkFromStep` copies the session through the node its history ended at when the turn did. A turn from before Mako recorded that node is imported."
      },
      "steering": {
        "state": "implemented",
        "via": "A prompt sent while a turn runs is read at its next step.",
        "lands": "step"
      },
      "compaction": {
        "state": "implemented",
        "via": "The harness's own compaction, started by Mako's Compact action."
      },
      "planning": {
        "state": "implemented",
        "via": "Its plan mode; the plan reaches Mako through write_plan's rendered plan file, built by answering exit_plan_mode's permission request. A reply to it is the next message: its plan approval is ACP's session/request_permission, whose answer is an option id, and devin 3000.10.23 reads no words with a rejection."
      },
      "approvals": {
        "state": "implemented",
        "via": "The harness asks and reports each decision it applied."
      },
      "questions": {
        "state": "implemented",
        "via": "The `ask_user_question` tool's request."
      },
      "modes": {
        "state": "implemented",
        "via": "ACP `session/set_mode`."
      },
      "nativeAgents": {
        "state": "implemented",
        "via": "`run_subagent` calls, whose usage arrives tagged with the subagent's ID."
      },
      "backgroundStop": {
        "state": "implemented",
        "via": "Stop kills each running background shell with killBackgroundShell, and its session/cancel ends each background subagent, with or without a running turn; no turn follows. Closing closes stdin, which ends them; a signal would leave them running."
      },
      "contextBreakdown": {
        "state": "absent",
        "by": "harness",
        "reason": "ACP's `usage_update` carries the context used and its size, nothing itemized."
      }
    },
    "usage": {
      "context": {
        "state": "implemented",
        "via": "ACP's `usage_update` from the main agent: what is in context."
      },
      "window": {
        "state": "implemented",
        "via": "The same `usage_update`'s `size`."
      },
      "compaction": {
        "state": "default",
        "reason": "Devin doesn't say what a compaction left, so the meter keeps its earlier reading, marked, until the next reply."
      },
      "tokens": {
        "state": "implemented",
        "via": "The tokens in each `usage_update`'s `_meta`."
      },
      "cost": {
        "state": "absent",
        "by": "harness",
        "reason": "Devin's usage updates carry no cost."
      },
      "missedCalls": {
        "state": "absent",
        "by": "harness",
        "reason": "Devin's usage updates never say they left a call out."
      },
      "resetCredits": {
        "state": "absent",
        "by": "harness",
        "reason": "Devin's usage report has no reset credits."
      },
      "contextBreakdown": {
        "state": "absent",
        "by": "harness",
        "reason": "ACP's `usage_update` carries the context used and its size, nothing itemized."
      },
      "outsideMako": {
        "state": "implemented",
        "via": "Settings › Usage reads its own store, so sessions run outside Mako count too."
      }
    }
  }
]
